[package]
name = "bunny_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
tokio = { version = "1.45.1", features = ["full"] }
rand = "0.8"
tyche = "0.3.1"
url = "2.5.4"
reqwest = { version = "0.12.18", features = ["json"] }
serde_json = "1.0.140"
serde = "1.0.219"

